#!/system/bin/sh
#===============================================================================
#
#  sysinfo
#
#  Copyright (C) 2016-2019 by Digi International Inc.
#  All rights reserved.
#
#  This program is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License version 2 as published by
#  the Free Software Foundation.
#
#
#  !Description: System information gather script
#
#===============================================================================

spaces(){
	echo ""
	echo ""
}

write_environment_table(){
	banner "ENVIRONMENT TABLE"

	echo "||*Component*|*Version*"
	echo "|| DUT | SN-${BOARD_SN}, ${MACHINE} ${BOARD_VARIANT} SBCv${BOARD_VERSION} board_ID=${BOARD_ID}."
	echo "|| U-Boot | ${UBOOT_VERSION}"
	echo "|| Firmware | ${DEA_VERSION}-${DEA_BUILD}"
	echo "|| Kernel | ${KERNEL_VERSION}"
	[ -n "${MCA_VERSION}" ] && echo "|| MCA | ${MCA_VERSION}"
	# Show, for repositories that belong to the group 'sysinfo', name and version (in table format)
	sed -ne '/groups=.*sysinfo/{s,.*name="\([^"]*\)".*revision="\([^"]*\)".*,|| \1 | \2,g;T;p}' /vendor/etc/repo-manifest.xml
	spaces
}

banner() {
	format="
--------------------------------------
-                                    -
- %-34s -
-                                    -
--------------------------------------

"
	printf "${format}" "${1}"
}

make_report(){
	banner "Kernel version"
	echo "${KERNEL_VERSION}"
	spaces

	banner "Repo manifest"
	cat /vendor/etc/repo-manifest.xml
	spaces

	banner "U-boot saved environment"
	fw_printenv 2>&1 || echo "[FAILED] fw_printenv"
	spaces

	banner "Getprop"
	getprop || echo "[FAILED] getprop"
	spaces

	banner "Linux boot log"
	dmesg || echo "[FAILED] dmesg"
	spaces

	banner "Logcat main"
	logcat -b main -d
	spaces

	banner "Logcat system"
	logcat -b system -d
	spaces

	banner "Logcat radio"
	logcat -b radio -d
	spaces

	banner "Logcat events"
	logcat -b events -d
	spaces

	banner "Logcat crash"
	logcat -b crash -d
	spaces

	banner "Linux kernel configuration"
	gzip -dc /proc/config.gz || echo "[FAILED] gzip"
	spaces

	banner "Dumpsys meminfo"
	dumpsys meminfo -d || echo "[FAILED] dumpsys meminfo"
	spaces

	banner "Dumpsys input"
	dumpsys input || echo "[FAILED] dumpsys input"
	spaces

	banner "Dumpsys display"
	dumpsys display || echo "[FAILED] dumpsys display"
	spaces

	banner "Dumpsys cpuinfo"
	dumpsys cpuinfo || echo "[FAILED] dumpsys cpuinfo"
	spaces

	banner "Dumpsys adc"
	dumpsys com.android.server.adc.IADCService || echo "[FAILED] dumpsys adc"
	spaces

	banner "Dumpsys can"
	dumpsys com.android.server.can.ICANService || echo "[FAILED] dumpsys can"
	spaces

	banner "Dumpsys gpio"
	dumpsys com.android.server.gpio.IGPIOService || echo "[FAILED] dumpsys gpio"
	spaces

	banner "Dumpsys i2c"
	dumpsys com.android.server.i2c.II2CService || echo "[FAILED] dumpsys i2c"
	spaces

	banner "Memory consumption"
	free || echo "[FAILED] free"
	spaces

	banner "Running processes"
	ps -T || echo "[FAILED] ps"
	spaces

	banner "Mounts"
	mount || echo "[FAILED] mount"
	spaces

	banner "Uptime"
	uptime || echo "[FAILED] uptime"
	spaces

	banner "Opened ports"
	netstat -n -l || echo "[FAILED] netstat"
	spaces

	banner "Routes"
	netstat -rne || echo "[FAILED] route"
	spaces

	banner "Network configuration"
	ifconfig -a || echo "[FAILED] ifconfig"
	spaces

	banner "Wireless configuration"
	/vendor/bin/hw/wpa_supplicant -v 2>/dev/null
	for file in /etc/wifi/*.conf /vendor/etc/wifi/*.conf; do
		[ -d $(dirname "${file}") ] && [ $(ls -A "${file}") ] || continue
		echo ""
		echo "$file:"
		cat "$file"
	done

	echo ""
	hostapd_cli -v 2>&1
	spaces

	banner "TrustFence"
	OTP_CFG5="$(cat /sys/fsl_otp/HW_OCOTP_CFG5 2>&1)"
	if [ "$?" = 0 ]; then
		if [ "$((${OTP_CFG5} & 2))" != "0" ]; then
			echo "Device status: [CLOSED]"
		else
			echo "Device status: [OPEN]"
		fi
	else
		echo "Device status: unknown (${OTP_CFG5})"
	fi

	if [ -f "/proc/device-tree/digi,uboot-env,encrypted" ]; then
		echo "U-Boot environment is encrypted"
	else
		echo "U-Boot environment is NOT encrypted"
	fi

	echo "-------------End of report------------"
}

DEA_VERSION="dea_version_undefined"
UBOOT_VERSION="uboot_version_undefined"
BOARD_VARIANT="board_variant_undefined"
BOARD_SN="board_sn_undefined"
BOARD_VERSION="board_version_undefined"
BOARD_ID="board_id_undefined"
DEA_BUILD="dea_build_undefined"
KERNEL_VERSION="kernel_version_undefined"
DATE="00000000000000"

DEA_VERSION="$(getprop ro.build.id 2> /dev/null)"
DEA_BUILD="$(getprop ro.build.version.incremental 2> /dev/null)"

UBOOT_VERSION="$(cat /proc/device-tree/digi,uboot,version 2>/dev/null)"
if [ -z "${UBOOT_VERSION}" ]; then
	[ -b /dev/block/mmcblk0boot0 ] && UBOOT_VERSION="$(strings /dev/block/mmcblk0boot0 | grep dub -m1 | cut -d' ' -f2)"
fi
[ -f /proc/device-tree/digi,machine,name ] && MACHINE="$(cat /proc/device-tree/digi,machine,name)"
[ -f /proc/device-tree/digi,hwid,variant ] && BOARD_VARIANT="$(cat /proc/device-tree/digi,hwid,variant)"
[ -f /proc/device-tree/digi,hwid,sn ] && BOARD_SN="$(cat /proc/device-tree/digi,hwid,sn)"
[ -f /proc/device-tree/digi,carrierboard,version ] && BOARD_VERSION="$(cat /proc/device-tree/digi,carrierboard,version)"
[ -f /proc/device-tree/digi,carrierboard,id ] && BOARD_ID="$(cat /proc/device-tree/digi,carrierboard,id)"

KERNEL_VERSION="$(uname -a)"

if grep -qs 'digi,ccimx8x' /proc/device-tree/compatible; then
	MCA_NODE="/sys/bus/i2c/devices/0-0063"
fi
if [ -d "$MCA_NODE" ]; then
	MCA_HW_VERSION=$(cat ${MCA_NODE}/hw_version 2>/dev/null | tr -d '\0') || MCA_HW_VERSION="??"
	MCA_FW_VERSION=$(cat ${MCA_NODE}/fw_version 2>/dev/null | tr -d '\0') || MCA_FW_VERSION="??"
	MCA_VERSION="HW_VERSION=${MCA_HW_VERSION}  FW_VERSION=${MCA_FW_VERSION}"
fi

[ -f /system/bin/date ] && DATE="$(date "+%Y%m%d%H%M%S")"
REPORT_PATH="/sdcard/Download/sysinfo-${DEA_VERSION}-${BOARD_SN}-${DATE}"

write_environment_table

if touch "${REPORT_PATH}.txt" 2> /dev/null; then
	write_environment_table >> "${REPORT_PATH}.txt"

	make_report >> "${REPORT_PATH}.txt"
	tar -zhcf "${REPORT_PATH}.tar.gz" -C $(dirname ${REPORT_PATH}) $(basename "${REPORT_PATH}.txt") /proc/device-tree 2> /dev/null
	echo "Report generated in ${REPORT_PATH}.tar.gz"
	rm -rf "${REPORT_PATH}.txt"
else
	echo "$(dirname ${REPORT_PATH}) is not writtable, skipping report generation"
fi
